;definitions for the transformation-routines of the ALPINE 3D-Engine
;written in spring and summer 1997 by Ziron

GLOBAL	RotateObjectInWorldSpace:PROC
GLOBAL	RotateObjectInObjectSpace:PROC
GLOBAL	TranslateObjectInWorldSpace:PROC
GLOBAL	TranslateObjectInObjectSpace:PROC

GLOBAL	RotateCameraInWorldSpace:PROC
GLOBAL	RotateCameraInCameraSpace:PROC
GLOBAL	TranslateCameraInWorldSpace:PROC
GLOBAL	TranslateCameraInCameraSpace:PROC

