!if $d(DEBUG)
ASMDEBUG=/zi
LINKDEBUG=/v
!else
ASMDEBUG=
LINKDEBUG=
!endif

.asm.obj:
    tasm /m $(ASMDEBUG) $<

NOTHING.EXE: NOTHING.OBJ 3DMAIN.OBJ 3DTRANSF.OBJ 3DPEN.OBJ\
             A3D_READ.OBJ SCREEN.OBJ
     tlink /3 /x $(LINKDEBUG) @NOTHING.RSP

NOTHING.OBJ:   NOTHING.ASM
3DMAIN.OBJ:    3DMAIN.ASM
3DTRANSF.OBJ:  3DTRANSF.ASM
3DPEN.OBJ:     3DPEN.ASM
A3D_READ.OBJ:  A3D_READ.ASM
SCREEN.OBJ:    SCREEN.ASM